### ISSUE TITLE
Why no post description/text data?

### ISSUE THREAD

**Issue by metamas** [oorestisime/gatsby-source-instagram#10]
Why is the Instagram post text/description not an included field? Is that data not provided by the Instagram API?

I'm working on a project that the designer included IG post text in. Any thoughts on how I might retrieve that data for my component?

**Comment by oorestisime** [comment]
Yes it is provided both in the graph api and the scrapping method, just didn't think of including it yet! i'll work on this in the following days and release a new version.

**Comment by metamas** [comment]
Thank you thank you! :)
