### ISSUE TITLE
Inject ID to hyperlink of Instagram Post

### ISSUE THREAD

**Issue by PHironaka** [oorestisime/gatsby-source-instagram#12]
I'm trying to add hyperlinks to each IG post, but am having issues injecting the post id to the link. So far I've had variations of the following but nothing works:

`<a href='https://www.instagram.com/p/{node.id}> `   

Any chance you could include a node which includes the full link to each post?

**Comment by oorestisime** [comment]
Hm weird, I am using `https://www.instagram.com/p/${img.node.id}` and didn't encounter any issue yet.
what issues did you encounter?

**Comment by PHironaka** [comment]
@oorestisime It wouldn't append the id to the string properly. The solve I came up with was wrapping the entire string around curly brackets:

`{https://www.instagram.com/p/${node.id}}`
