### ISSUE TITLE
Discussion: Deprecation of the Instagram legacy API

### ISSUE THREAD

**Issue by timrodz** [oorestisime/gatsby-source-instagram#131]
I found out that  Instagram is [deprecating their legacy API](https://www.instagram.com/developer/) on March 31, 2020. Would this affect how this plugin works?

If so, looks like we'll have to migrate to the [Basic Display API](https://developers.facebook.com/docs/instagram-basic-display-api). The [User Token Generator](https://developers.facebook.com/docs/instagram-basic-display-api/overview#user-token-generator) generates a token that is valid for 60 days before having to be refreshed, and can **only** be used with accounts you know the credentials to.

**Comment by oorestisime** [comment]
The plugin is using the graph api when provided with a token so i think that this deprecation is ok for the plugin. 
I am not sure whether they will change anything for the public scraping. I ll keep a close eye on that during that day.

Btw if you want to generate a token here's a how to https://github.com/oorestisime/gatsby-source-instagram#instagram-graph-api-token

**Comment by timrodz** [comment]
Thanks for the heads up @oorestisime. I think it _might_ affect the public scraping part.

I'm working on this [gatsby starter](https://github.com/timrodz/gatsby-starter-instagram-baseweb). If I keep using this plugin, what do you think will be the steps for setting up with the new graph API? 

Currently, my setup on `gatsby-config.js` is meant to work publicly:

```js
{
  resolve: `gatsby-source-instagram`,
  options: {
    username: config.social.instagram,
  },
}
```

**Comment by oorestisime** [comment]
Unfrotunately i won't be able to predict those changes so maybe we will have some issues that day. hopefully not!

As for the graph api i sent you above the way to get a token. Once you get what you need you can configure it in a similar manner as i do in the example:
https://github.com/oorestisime/gatsby-source-instagram/blob/master/example/gatsby-config.js#L16-L22

**Comment by timrodz** [comment]
Cheers for the link!

**Comment by redraw** [comment]
This doesn't seem to be official, but it has been working for a long time, and data is public anyway.

If you append `?__a=1` to any profile/hashtag page you'll get a graphql JSON response.

**Comment by oorestisime** [comment]
ha interesting, hope to have some time in the following days to do this then. unless you want to PR :)

**Comment by oorestisime** [comment]
I am closing this issue since it hasn't impacted anything on the plugin
