### ISSUE TITLE
childImageSharp

### ISSUE THREAD

**Issue by j-per** [oorestisime/gatsby-source-instagram#138]
Hello,

Is it possible to use the childImageSharp fluid rather than fixed with this plugin?

**Comment by oorestisime** [comment]
Hey there, yeah it is!
Have a look at the example https://github.com/oorestisime/gatsby-source-instagram/search?q=fluid&unscoped_q=fluid

**Comment by j-per** [comment]
Awesome! Thanks a bunch.
