### ISSUE TITLE
Error when getting permanent page access token in Graph API Explorer

### ISSUE THREAD

**Issue by crhallen** [oorestisime/gatsby-source-instagram#145]
When I follow the **Instagram Graph API token** instructions, I get stuck at step 6 ii) 
> Make a GET request with "PAGE_ID?fields=access_token"

The GET request returns the following error:
```
{
  "error": {
    "message": "(#100) Page Public Metadata Access requires either app secret proof or an app token",
    "type": "OAuthException",
    "code": 100,
    "fbtrace_id": "Ai90-u47JI4T4pGEG8aCkwq"
  }
}
```
I have tried restarting the instructions from scratch a couple of times to double check and I get the same error each time.  Is there something I could be missing?

**Comment by oorestisime** [comment]
Hm I can't recall ever seeing this kind of error. 
Seems to be something wrong with the permissions. Did you select the correct ones in step 4 here https://github.com/oorestisime/gatsby-source-instagram#instagram-graph-api-token ?

**Comment by crhallen** [comment]
Aha, figured out I wasn't pressing the "Generate Access Token" button after setting the permissions in 4ii).  Solved now, thank you!  Here's a PR to add that step to the docs in case anyone misses it like me https://github.com/oorestisime/gatsby-source-instagram/pull/146
