### ISSUE TITLE
Failing on Netlify builds, why?

### ISSUE THREAD

**Issue by ColinTS** [oorestisime/gatsby-source-instagram#154]
I use Netlify with Gatsby and while this plugin used to work I now get a Netlify error saying "cannot query allInstaNode" on "Query". Must be related, but I see on your Github page that Netlify build is failing for this plugin. Are you aware? Is there a fix? Thanks.

![Deploy_details_blissful_lamarr_a6ba57](https://user-images.githubusercontent.com/22946431/83582904-c204c480-a53a-11ea-9851-fe3fff1b9250.png)

**Comment by NeversSync** [comment]
Having the same issue. Was working a few days ago

**Comment by zambo** [comment]
Same here

**Comment by oorestisime** [comment]
Duplicate of #24
