### ISSUE TITLE
manage_pages not available in Graph API Explorer

### ISSUE THREAD

**Issue by peterfortuin** [oorestisime/gatsby-source-instagram#156]
When I try to follow the steps to get an access token for this plugin, I get stuck by adding the manage_pages permission. It seems that it's not available. Maybe they removed it?

**Comment by oorestisime** [comment]
Are all the permission or just that one? If just that i would continue maybe they removed it. Also if you go through all the steps please report here if something is inconsistent so we can fix this :)

**Comment by peterfortuin** [comment]
The managepages permission is missing. pagesshowlist and instagrambasic permissions are in the list. 
If I continue I run into trouble in step 6. After the get request I always get the following error:

` Page Public Metadata Access requires either app secret proof or an app token `

**Comment by oorestisime** [comment]
So it seems it got replaced a month ago https://developers.facebook.com/docs/facebook-login/permissions/#reference-manage_pages
I would add the other permissions it lists there. 
Please let me know if that works :)

**Comment by peterfortuin** [comment]
I have added the pages_manage_* permissions and that seems to resolve my problem. Not sure if they are all required. Probably not.

**Comment by oorestisime** [comment]
yeah that would be too many permissions i think. probably the ones that list there would suffice. Was there anything you found problematic in that docs section? 
I would happily accept a PR or do it myself for the permissions already.

**Comment by oorestisime** [comment]
Permissions needed are pages_manage_ads, pages_manage_metadata, pages_read_engagement, pages_read_user_content, pages_show_list, instagram_basic
closing this
