### ISSUE TITLE
Gatsby builds are failing for Profile

### ISSUE THREAD

**Issue by TS000** [oorestisime/gatsby-source-instagram#159]
https://app.netlify.com/sites/gatsby-src-instagram/deploys
![Screen Shot 2020-06-12 at 7 58 23 PM](https://user-images.githubusercontent.com/12666836/84557306-26681680-ace7-11ea-912d-0dac23b539d1.png)

https://gatsby-src-instagram.netlify.app/profile
![Screen Shot 2020-06-12 at 7 59 27 PM](https://user-images.githubusercontent.com/12666836/84557315-3e3f9a80-ace7-11ea-9d34-93c624c1eb74.png)

The other features seem to be working but Profile is failing on Gatsby build (it works on my local env).

**Comment by oorestisime** [comment]
#24
