### ISSUE TITLE
Multiple Instagram Accounts

### ISSUE THREAD

**Issue by marcelmouse** [oorestisime/gatsby-source-instagram#16]
How can I pass multiple usernames into the plugin? Can the user name be a list of names or maybe a variable that I can access from a template?

```
    {
       resolve: 'gatsby-source-instagram',
       options: {
         username: nameOfUser
       },
     },
```

I need to show different instagram data depending on the slug...

```
  query artistQuery($slug: String!) {
    allInstaNode {
      edges {
       node {
         id
         likes
         comments
         mediaType
         preview
         original
         timestamp
         caption
         localFile {
           childImageSharp {
             fixed(width: 150, height: 150) {
               ...GatsbyImageSharpFixed
             }
           }
         }
        }
      }
    }
  }
```

**Comment by oorestisime** [comment]
hm interesting,
maybe you can define two instagram plugins?

```
{
  resolve: 'gatsby-source-instagram',
  options: {
    username: 'instagram'
  }
},
{
  resolve: 'gatsby-source-instagram',
  options: {
    username: 'instagram2'
  }
},
```

I will need to add the username in the available fields. would this work for you?

**Comment by marcelmouse** [comment]
hmm. thanks for replying so quickly!

i think what i am looking to do is to be able to use the instagram query with variable data which I am pulling in from a CMS. so instead of declaring the `username` in the gatsby-config file i would want to declare it in the gatsby-node file or in a query inside the template file. 

does this make sense? 

i might just have to query instagram from `componentDidMount()` without a plugin but if you have any ideas on the best way to go about this let me know!

**Comment by oorestisime** [comment]
if you are ok with the refresh rate of your instagram posts only on build time i suppose you can create a staticquery that filters your `allInstaNode` as you wish. when plugin runs you pull in all data and then with static queries you handle which nodes you use.

**Comment by marcelmouse** [comment]
ok. thanks for your help!

**Comment by oorestisime** [comment]
So do you need username in the available fields in order to filter on it? or are you using something different in the end?

**Comment by marcelmouse** [comment]
i think i am just going to make the fetch the posts from component did mount because i need it for each template and i have access to the user name there

**Comment by oorestisime** [comment]
right ok! i don't mind adding the username as an available field. but if you did want a better refresh rate then componentDidMount seems like the best choice!
