### ISSUE TITLE
Getting instagram ID

### ISSUE THREAD

**Issue by tobinharris** [oorestisime/gatsby-source-instagram#161]
In the 0.8 release notes, the tool for getting your numeric Instagram ID doesn't seem to work.

I found this one after hunting around.

https://www.instafollowers.co/find-instagram-user-id

Hope this helps!

**Comment by andregmoeller** [comment]
I have opened a [PR](https://github.com/oorestisime/gatsby-source-instagram/pull/160), which explains how to determine the Instagram ID without using another service.

See also [Issue #24 – Comment 646361767](https://github.com/oorestisime/gatsby-source-instagram/issues/24#issuecomment-646361767) respectively [Issue #24 – Comment 646517691](https://github.com/oorestisime/gatsby-source-instagram/issues/24#issuecomment-646517691).
