### ISSUE TITLE
sourced image URL expires after a few days

### ISSUE THREAD

**Issue by dkocich** [oorestisime/gatsby-source-instagram#168]
I use the plugin to get URLs of IG images which I then show in my static page. The problem is that after a while they stop loading and their response is "URL signature expired" (I use `allInstaNodes.edges.map( (e)=> ... <img src={e.node.thumbnails.src}...` 

possible solutions 
- save images to the build folder and serve it statically with the build 
- use different URL while loading? e.g. https://stackoverflow.com/a/53750300/4114514

**Comment by oorestisime** [comment]
You can already use sharp to download images and resize etc. i think this is already covered.
