### ISSUE TITLE
Cannot read property 'edge_owner_to_timeline_media'

### ISSUE THREAD

**Issue by danny-waite** [oorestisime/gatsby-source-instagram#169]
Getting an issue with version `0.8.0` when building, both on Gatsby Cloud and locally. `0.7.0` works fine but it looks like Gatsby Cloud enforces the latest version of a plugin?

I've tried several Instagram accounts

Could not fetch instagram posts. Error status TypeError: Cannot read property 'edge_owner_to_timeline_media' of null

**Comment by flox1an** [comment]
I have the same issue after upgrading to 0.8.0

**Comment by oorestisime** [comment]
Did you change the username in instagram? there were some breaking changes https://github.com/oorestisime/gatsby-source-instagram/releases/tag/v0.8.0
