### ISSUE TITLE
How to dynamically load new images

### ISSUE THREAD

**Issue by ergunpp** [oorestisime/gatsby-source-instagram#17]
Hi,
I have used this plugin with my website and it works fine. But it only queries the posts at build time, when the page is built, new images posted after build time are not fetched.
Is there a way to do this dynamically?
Thanks

**Comment by oorestisime** [comment]
No there is no way to do this, as is the case with the rest of the gatsby plugins.
What you can do is build regularly your website, builds are supposed to be fast and you should be able to schedule more than 1 per day for example.

**Comment by ergunpp** [comment]
Is it possible to set up a hook for instagram posts?

**Comment by oorestisime** [comment]
Do you have an example of another gatsby plugin providing a hook or anything? i could look how to do this

**Comment by oorestisime** [comment]
Actually even if i could add a hook that provides a wrap of the API etc, it wouldn't make much sense since you wouldn't be able to profit from the graphql and image processing.

I am closing this issue, feel free to open this again if you feel something could be done in the scope of this plugin!

**Comment by tkstang** [comment]
@ergunpp You should be able to set up a web hook that triggers any time a new post is made to a given account which makes an http request triggering your build.  I'm deploying a a website I'm working on over the weekend and had planned on doing this, I would be happy to report back if you're interested.

**Comment by ergunpp** [comment]
Yes pls I would be glad

**Comment by tkstang** [comment]
@ergunpp It looks like instagram no longer supports the web hook they used to for "new media posts" to an account - they did previously.  You can however do this via zapier, and the number of "zaps" you get on the free tier should be sufficient for what you want to accomplish unless the account in question is posting in excess of 100 posts a month.  You get 100 'tasks' a month on the free tier.  You are charged every time the task is run which would in this case be any time new media is posted to the account.  $20/month gets you 1000.  Alternatively you could just schedule a daily build as @oorestisime mentioned with netlify.  I also believe you can set up IFTTT to hit the netlify build endpoint for your site and you could easily just build by pressing a button on your phone whenever you wanted.  This of course would require you to remember to do so.
