### ISSUE TITLE
Use maxPosts for scraping method

### ISSUE THREAD

**Issue by greatwitenorth** [oorestisime/gatsby-source-instagram#180]
It looks like the scraping method is not using the `maxPosts` config. It's currently hard coded to 100:

https://github.com/oorestisime/gatsby-source-instagram/blob/8e104fb3a4105187e5d67c69560cfea0cc7c56e0/src/instagram.js#L5-L8

Can we use the `maxPosts` config here?

**Comment by oorestisime** [comment]
No we can't because we cant paginate their page :( 
also given all the issues right now with public scraping i am not sure i want to touch this :/
