### ISSUE TITLE
Build works fine locally, but fails on Gatsby Cloud

### ISSUE THREAD

**Issue by maweo-mathis** [oorestisime/gatsby-source-instagram#222]
Hello,

I am using the plugin for public scraping for posts from our Instagram page. I configured the plugin like that:
```
{
      resolve: `gatsby-source-instagram`,
      options: {
        username: `80636XXXX`,
      },
},
```

Locally when i run `gastby build` everything works perfectly, but in the Gatsby cloud the build fails with the following error:
11:07:12 AM:
ERROR There was an error in your GraphQL query:

11:07:12 AM:
Cannot query field "allInstaNode" on type "Query".

Package.json
```
"dependencies": {
  "gatsby-source-instagram": "^0.9.0",
}
```

**Comment by graysonhicks** [comment]
This is normally a sign that the rate limit from Instagram prevented nodes from being sourced.

**Comment by VMargreiter** [comment]
i generally think that this might also be the deprecated "scraping-for-user profile" issue

**Comment by graysonhicks** [comment]
Yea, fair to note that almost all attempts to use the Instagram API are going to be thwarted at some point.  Not unique to this plugin 😞

**Comment by graysonhicks** [comment]
@oorestisime I believe this is due to rate limiting and can be closed.   There is possibly a solution using the Gatsby `cache` object to reduce the amount of fetching for most builds, but can be handled separately as users should associated this with the error message provided in the README.  I believe this should be closed.

**Comment by graysonhicks** [comment]
More specifically, this can happen on any cloud build pipeline service because their IP range may be used very often to hit the API (not just your site building, but 100s of others).  So Instagram blocks that IP range for abuse.  The only way around is with the authenticated API.
