### ISSUE TITLE
Extend the Facebook/Instagram access token time

### ISSUE THREAD

**Issue by mrruby** [oorestisime/gatsby-source-instagram#223]
I can only extend the Facebook/Instagram access token to two months, is there any other way to create one valid for a longer period of time?

**Comment by listiani13** [comment]
I follow guide on this page and seems to work for me https://developers.facebook.com/docs/pages/access-tokens/ (getting the page access token, so it never expires)

**Comment by graysonhicks** [comment]
What @listiani13 said is correct.  Following that guide should avoid any expiration, and either way, is outside the scope of what this plugin can do (it doesn't create the token).

@oorestisime I believe this can be closed.
