### ISSUE TITLE
Error while running the sourceNodes lifecycle

### ISSUE THREAD

**Issue by listiani13** [oorestisime/gatsby-source-instagram#230]
Hey, thank you for creating this wonderful package! However, I run into this error since today's build. Is this related to instagram API behavior? Thank you!
<img width="577" alt="image" src="https://user-images.githubusercontent.com/24470609/161367864-d1384bec-1e6a-41cb-90a6-3e1baf122f5b.png">

**Comment by bkamphues** [comment]
I'm experiencing this issue as well!

**Comment by graysonhicks** [comment]
Added a fix for this here: https://github.com/oorestisime/gatsby-source-instagram/pull/238
