### ISSUE TITLE
Maintenance

### ISSUE THREAD

**Issue by pak11273** [oorestisime/gatsby-source-instagram#232]
Is this library being maintained anymore?  Looks like a lot of the PRs have gone stale.

**Comment by oorestisime** [comment]
Unfortunately i dont have time for it anymore :(
I am also on holiday right now.

**Comment by graysonhicks** [comment]
@oorestisime I am open to maintaining if you want to discuss transferring Github and NPM ownership!

**Comment by oorestisime** [comment]
I ll try to dedicate some time into reviewing PRs and what not. lets see how this rides
