### ISSUE TITLE
Images load in arbitrary order

### ISSUE THREAD

**Issue by axelengstrom** [oorestisime/gatsby-source-instagram#25]
I'm using the public scraping method but the images doesn't seem to load in a chronological order, which makes it hard to limit the amount of nodes already in the graphql-query. 

My goal is to receive the three latest images from an instagram account. Is there any way to achieve this? Or do I have to load 12 images, sort them and then iterate? (Which is what I did now)

Thanks!

**Comment by oorestisime** [comment]
Am not sure i get this right. are you looking to filter and limit by 3 in the graphql query? or you mean not even creating 12 nodes in the first place but just 3?

**Comment by axelengstrom** [comment]
The latter, I want to recieve only the three latest images from a specific user

**Comment by oorestisime** [comment]
how about something like:
```
{
  allInstaNode(sort: {order: DESC, fields: timestamp}, limit: 3) {
    edges {
      node {
        id
        timestamp
        username
      }
    }
  }
}
```

would it solve your issue? Right now there is no limit in how many nodes to create. maybe i should add.

**Comment by axelengstrom** [comment]
Ah, of course... I never thought of combining the sort and limit arguments. It solves my issue.
Many thanks!
