### ISSUE TITLE
Expose Video format url

### ISSUE THREAD

**Issue by JeuelyFish** [oorestisime/gatsby-source-instagram#26]
Really enjoying how easy and straight forward this plugin is to use. I am having some trouble, however, trying to access video content.

For example, I can query my recent posts and see that there are video types there with

```
{
  allInstaNode {
    edges {
      node {
        mediaType
      }
    }
  }
}
```

When exploring its available data in the GraqhiQL editor tho, I'm not able to find any URL or localFile that points to any mp4 or other video format files. It would be nice to expose this feature.

**Comment by oorestisime** [comment]
Hey there, I don't have any videos to test this (can you provide me with a username?)
But have you tried the `preview` and `original` properties?

**Comment by oorestisime** [comment]
@JeuelyFish any news here?

**Comment by oorestisime** [comment]
Closing this, dont hesitate to re-open with more information :)

**Comment by willmcl** [comment]
Hi, I am having the same problem. _purepops_icepops_ has some videos on there you could use to test?
