### ISSUE TITLE
Integration with gatsby-image

### ISSUE THREAD

**Issue by m4rcelofs** [oorestisime/gatsby-source-instagram#3]
While having the thumbnail urls is great, I'd love to use the full image as source for gatsby-image (specially because of lazy-load and avoiding company firewalls blocking instagram urls on visitors).

Apparently [gatsby-source-contentful](https://github.com/gatsbyjs/gatsby/tree/master/packages/gatsby-source-contentful) and [gatsby-source-datocms](https://github.com/datocms/gatsby-source-datocms#integration-with-gatsby-image) already do something similar.

I'm new at gatsby and its plugins, but it seems conceivable. Would a PR for this be welcome? Any pointers on how I should get started?

**Comment by oorestisime** [comment]
Hello,

I ve already started working on this, i hope to have it ready soon. I am also new to gatsby :) so i wouldn't know how to give you any pointers.

**Comment by oorestisime** [comment]
So, i think i have working the gatsby-image part. I basically create the srcsets etc based on the available thumbnails and the original img (so no resizing etc) so that the lazy loading works.
I still need to download locally the images and cache them so that at the build the images are not fetched from instagram

**Comment by oorestisime** [comment]
Hey so i ve refactored everything from this morning. you should be able to now use gatsby image and download locally everything. Please have a look at the readme for details and let me know if things work for you as expected!

**Comment by m4rcelofs** [comment]
Just tried it with fluid images and works flawlessly, thanks!

**Comment by rchrdnsh** [comment]
I can't seem to get this to work. This is what I'm doing:

```
allInstaNode(sort: { fields: [timestamp], order: DESC }) {
      edges {
        node {
          id
          likes
          comments
          mediaType
          preview
          original
          timestamp
          caption
          localFile {
            childImageSharp {
              fluid(maxWidth: 256) {
                ...GatsbyImageSharpFluid
              }
            }
          }
          thumbnails {
            src
            config_width
            config_height
          }
          dimensions {
            height
            width
          }
        }
      }
    }
```

then in my component:

```
<InstaGrid>
        {data.allInstaNode.edges.map(({ node }) => (
          <InstaPost key={node.id}>
            <InstaSpacer>
              <InstaLikes>❤️ {node.likes}</InstaLikes>
              <InstaComments>💬 {node.comments}</InstaComments>
              <InstaScrim />
              {/* <InstaImage src={node.original} /> */}
              <InstaImage src={node.localFile.childImageSharp.fixed} />
            </InstaSpacer>
          </InstaPost>
        ))}
      </InstaGrid>
```

If i just get the original or thumbnail it works, but if I switch over to localFile etc...the images don't work anymore...anything i should be doing differently?

**Comment by oorestisime** [comment]
hey there,
In your query you are asking for fluid but then on the gatsby image you seem to be passing fixed.

**Comment by rchrdnsh** [comment]
apologies, yes, i tired both but copied from the wrong one. Neither fixed nor fluid seem to be working for me, but original does...but alas, without image optimization :-(

app screenshot with either fixed or fluid queries:

<img width="413" alt="Screen Shot 2019-06-08 at 11 33 15 PM" src="https://user-images.githubusercontent.com/7884263/59155808-cd1b3680-8a45-11e9-8927-32d356e43f83.png">

**Comment by oorestisime** [comment]
maybe you have a repo i can look? not sure what InstaImage is for example.

**Comment by rchrdnsh** [comment]
sure:

https://github.com/arrowgtp/alma

also, `<InstaImage>` is a styled component for the image itself, which looks like this:

```
const InstaImage = styled.img`
  grid-row: 1 / 9;
  grid-column: 1 / 9;
  margin: 0;
  padding: 0;
  border-radius: 16px;
  object-fit: cover;
  width: 100%;
  height: 100%;
  z-index: 0;
`
```

is is a child of a grid item, but otherwise everything about it's css is pretty normal.

Also, just to re-iterate, if I load up this instead:

```
<InstaImage src={node.original} />
```

instead of:

```
<InstaImage src={node.localFile.childImageSharp.fluid} />
```

the images load just fine...just no dope gatsby image processing...and lighthouse yelled at me for it :-(

**Comment by oorestisime** [comment]
So you are not using gatsby image, just plain image tag!
have you looked at the gatsby image documentation?

**Comment by rchrdnsh** [comment]
I'm importing:

```
import Img from 'gatsby-image'
```

I think this is correct, but let me double check it really quick.

**Comment by oorestisime** [comment]
yeah but your styled-component is not using it! it is using `styled.img` should be `styled(Img)`

**Comment by rchrdnsh** [comment]
welp, looks like i'm not so smart! 😬

k, that fixed it, along with changing `src` to `fluid`, which i totally do elsewhere, but completely kerplunkt that one!

Thank you very much for your expedient help!

**Comment by oorestisime** [comment]
no worries! happy to help!
