### ISSUE TITLE
Graphql error: Cannot query 'allInstaNode' on type 'Query'

### ISSUE THREAD

**Issue by MilosJo** [oorestisime/gatsby-source-instagram#41]
My guess would be that  Instagram changed their API and/or markup and it cause `gatsby-source-instagram` to break. The error: 
```
GraphQL Error Encountered 1 error(s):
- Unknown field 'allInstaNode' on type 'Query'. 
```
Inside `GraphiQL` on `localhost:8000/__graphql`, 'allInstaNode' field doesn't exist.

**Comment by oorestisime** [comment]
This seems related to #42

**Comment by MilosJo** [comment]
Yeah, the timing of opening issues was like ~1min difference and people, including me, start to comment on issue #42.
