### ISSUE TITLE
Could the plugin cache posts to accelerate dev builds?

### ISSUE THREAD

**Issue by diegodorado** [oorestisime/gatsby-source-instagram#46]
When I build the site, it goes and download all related posts again... could this be cached so if post has not changed, it can use the cached version.
Mostly, to cache the images locally.

**Comment by oorestisime** [comment]
Hm this should have been working. Maybe something broke or gatsby changed something with the cache. i am going to have a look.

**Comment by oorestisime** [comment]
Hm, not sure i can reproduce this. i did gatsby develop on the example site, it went to download and parse all the images. i stopped and did again gatsby develop and it didn't download anything nor it `sharp`ed images. can you give a few more details on what you were facing?

**Comment by diegodorado** [comment]
I think this was an issue only that day when instagram was not working
properly....

**Comment by oorestisime** [comment]
Ok great! closing this!
