### ISSUE TITLE
Unknown field 'allInstaNode' on type 'Query'

### ISSUE THREAD

**Issue by YannickDot** [oorestisime/gatsby-source-instagram#48]
Hello 

Today my gatsby builds started crashing with this error : 
```
GraphQL Error Encountered 1 error(s):

- Unknown field 'allInstaNode' on type 'Query'.
```

It looks like it is the same problem as in #42 

But I don't know what changed in their markup.

I'm using the version 0.5.1.

**Comment by YannickDot** [comment]
Well nevermind, problem solved  🤔

I uninstalled and reinstalled the plugin 

```
yarn remove gatsby-source-instagram
``` 
and then 
```
yarn add gatsby-source-instagram
``` 
And it worked again.

I don't know what was the cause of my issue. 

Caching maybe?

**Comment by hzburki** [comment]
I get the same error in my Netlify build. The project runs fine using `gatsby develop`.

**Comment by oorestisime** [comment]
Please check #24
