### ISSUE TITLE
Experiment with the instagram api (REST and graphql)

### ISSUE THREAD

**Issue by oorestisime** [oorestisime/gatsby-source-instagram#7]
Right now plugin only supports web scraping and fetching instagram posts

It could be nice to have a way to interact with the instagram api to fetch posts (and or other things it can provide). I think that this should be optional and keep the current functionnality untouched.

* https://www.instagram.com/developer/
* https://developers.facebook.com/docs/instagram-api

**Comment by azamatsmith** [comment]
Hi, I'm doing this in a local plugin and can submit a PR if you like?

**Comment by oorestisime** [comment]
Hey,
i had a few hours tmr to work on that but if you already have something ready then why not!

**Comment by oorestisime** [comment]
Which api did you use? the rest api will disappear on December afaiu. i was planning to look the new graph api.

ah no sorry 2020 is the deprecation for reading persons posts

**Comment by azamatsmith** [comment]
Yeah that is the one that I use [here](https://github.com/wildsmithstudio/wildsmith/blob/a899eccb967a59de905a51c6143cbaf75d907419/plugins/wildsmith-source-instagram/gatsby-node.js#L15).

It requires a little work setting up the key, but I can reuse some documentation from a blog post I did.

**Comment by oorestisime** [comment]
Yeah could be nice to add in the readme how to set up the key. So go ahead with a PR for sure! And thanks!

**Comment by oorestisime** [comment]
Hey, any news on that? i was planning to work on that but then you showed interest so it seems the issue is stuck but i kinda need it :)

**Comment by azamatsmith** [comment]
Sorry, I won't be able to get to it for a while. Feel free to add it.

**Comment by oorestisime** [comment]
ok cheers, thanks for letting me know!

**Comment by oorestisime** [comment]
@azamatsmith hey sorry to nag you again, did you by any chance get access token for the graph api ? (or are they the same with the rest one?) i seem to have to upload screencast with apps and everything which is quite annoying and time consuming

**Comment by oorestisime** [comment]
never mind i managed to do it.
