### ISSUE TITLE
Dynamic username

### ISSUE THREAD

**Issue by eelkeh** [oorestisime/gatsby-source-instagram#76]
In my case the username is dynamic, right now it pulls the username from the config. Is it possible to use a dynamic username based on a query?

**Comment by oorestisime** [comment]
This plugin like any of gatsby runs on build time so not sure what you mean by dynamic. You could retrieve the username from an environment variable but i guess what you are looking for is changing even after gatsby develop or gatsby build?

**Comment by eelkeh** [comment]
By dynamic I mean something like retrieving the username from a page query! So let's say for example sake I want to generate different pages (at build time) which include a bunch of instagram pictures from different accounts, one account per page.

**Comment by oorestisime** [comment]
Right so if you take a look at the example https://github.com/oorestisime/gatsby-source-instagram/blob/master/example/gatsby-config.js#L16-L46 you can see you can define this plugin multiple times. You can do one for each username until i find some time to do #22 
Then in your page query you can do something like https://github.com/oorestisime/gatsby-source-instagram/blob/master/example/src/pages/scraping.js#L18 to retrieve only the posts of the username you wish.

Let me know if this is any help.

**Comment by oorestisime** [comment]
Closing this, if you think there's something to do in the plugin feel free to reopen :)
