### ISSUE TITLE
Public scraping returns "Cannot read property '0' of undefined"

### ISSUE THREAD

**Issue by zamson** [oorestisime/gatsby-source-instagram#99]
As of today I cannot fetch Instagram data with the public method. I have not made any changes to my code which has been working great the last month. When running gatsby develop I get this warning:

`warn
Could not fetch instagram posts. Error status TypeError: Cannot read property '0' of undefined`

**Comment by oorestisime** [comment]
Hey there, i ve just started a master build to check and everything seems to be working. any idea if this was a temporary error? or maybe some network error?

**Comment by zamson** [comment]
> Hey there, i ve just started a master build to check and everything seems to be working. any idea if this was a temporary error? or maybe some network error?

Like you say it seems like it might have been an error on Instagrams API. I just tried again and it's working again. Thanks for maintaining this plugin. All the best
